version: '3.8'

services:
  postgres:
    image: postgres
    container_name: pg
    ports:
      - "8080:8080"
    environment:
      POSTGRES_USER: golovanov
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 256m

  clickhouse:
    image: clickhouse/clickhouse-server
    container_name: ch
    ports:
      - "8123:8123"
    environment:
      CLICKHOUSE_USER: username
      CLICKHOUSE_PASSWORD: password
    volumes:
      - ./ch_data:/var/lib/clickhouse
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 256m